title: Programming, tech and magic from the black techno-monk of Pontrefact
description: > # this means to ignore newlines until "baseurl:"
  Journal for tech, programming and engineering projects by Ricardo Rojas.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rikimaru55.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ricardo Rojas # add your name
author-img: monk.png # add your photo
about-author: Black techno-monk of Pontrefact. Purveyor of alchemy, sorcery and a thousand wondrous things. During the week a mild-mannered software engineer. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rikimaru55 # add your Github handle
social-linkedin: ricardo-rojas-fernandez # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-151942119-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
